name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://web.mta.info/status/weekendstatus.js
          downloaded_filename: ./raw/weekendstatus.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://web.mta.info/status/weekendroutestatus.js
          downloaded_filename: ./raw/weekendroutestatus.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://web.mta.info/status/weekendboroughstatus.js
          downloaded_filename: ./raw/weekendboroughstatus.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://web.mta.info/weekender/Data/LinesStaticData.js
          downloaded_filename: ./raw/LinesStaticData.js
